/**
 * setup() で投入するモックデータ。実在しない情報のみ。
 * プロパティ名は SCHEMA の cols に合わせる（団体マスタの項目は values に入れる）。
 */
var MOCK_DATA = {
  sets: [
    { id: 'S001', name: '締結告知セット', description: 'パートナー締結時に、メール・SNS・note・HPニュースをまとめて作成します。', order: 1, active: true },
  ],
  ranks: [
    { name: 'ゴールド', order: 1, active: true },
    { name: 'シルバー', order: 2, active: true },
  ],
  media: [
    { id: 'M001', name: 'メール', order: 1, active: true },
    { id: 'M002', name: 'X', order: 2, active: true },
    { id: 'M003', name: 'Instagram', order: 3, active: true },
    { id: 'M004', name: 'note', order: 4, active: true },
    { id: 'M005', name: 'HPニュース', order: 5, active: true },
  ],
  mediaFields: [
    { mediaId: 'M001', fieldKey: '件名', label: '件名', limit: '', countMode: '通常', splitRule: 'なし', order: 1 },
    { mediaId: 'M001', fieldKey: '本文', label: '本文', limit: '', countMode: '通常', splitRule: 'なし', order: 2 },
    { mediaId: 'M002', fieldKey: '本文', label: '投稿本文', limit: 280, countMode: 'X方式', splitRule: 'スレッド分割', order: 1 },
    { mediaId: 'M003', fieldKey: '本文', label: 'キャプション', limit: 2200, countMode: '通常', splitRule: 'なし', order: 1 },
    { mediaId: 'M003', fieldKey: 'ハッシュタグ', label: 'ハッシュタグ', limit: '', countMode: '通常', splitRule: 'なし', order: 2 },
    { mediaId: 'M004', fieldKey: 'タイトル', label: 'タイトル', limit: '', countMode: '通常', splitRule: 'なし', order: 1 },
    { mediaId: 'M004', fieldKey: '本文', label: '本文', limit: '', countMode: '通常', splitRule: 'なし', order: 2 },
    { mediaId: 'M005', fieldKey: 'タイトル', label: 'タイトル', limit: '', countMode: '通常', splitRule: 'なし', order: 1 },
    { mediaId: 'M005', fieldKey: '本文', label: '本文', limit: '', countMode: '通常', splitRule: 'なし', order: 2 },
  ],
  dateFormats: [
    { label: '2026年9月24日', format: 'YYYY年M月D日', order: 1, active: true },
    { label: '2026年9月24日（木）', format: 'YYYY年M月D日（曜）', order: 2, active: true },
    { label: '9月24日', format: 'M月D日', order: 3, active: true },
    { label: '9/24(木)', format: 'M/D(曜)', order: 4, active: true },
    { label: '2026/09/24', format: 'YYYY/MM/DD', order: 5, active: true },
  ],
  items: [
    { key: '団体名', label: '団体名', category: '団体', type: '短文', options: '', format: '', required: true, defaultValue: '', example: 'サンプル団体', order: 1, active: true },
    { key: '団体区分', label: '団体区分', category: '団体', type: '選択', options: '学生団体,企業,自治体,その他', format: '', required: false, defaultValue: '学生団体', example: '学生団体', order: 2, active: true },
    { key: '代表者名', label: '代表者名', category: '団体', type: '短文', options: '', format: '', required: false, defaultValue: '', example: '見本 太郎', order: 3, active: true },
    { key: '団体URL', label: '団体の公式URL', category: '団体', type: 'URL', options: '', format: '', required: false, defaultValue: '', example: 'https://example.com', order: 4, active: true },
    { key: 'Xアカウント', label: 'Xアカウント', category: '団体', type: '短文', options: '', format: '', required: false, defaultValue: '', example: '@sample_account', order: 5, active: true },
    { key: 'Instagramアカウント', label: 'Instagramアカウント', category: '団体', type: '短文', options: '', format: '', required: false, defaultValue: '', example: '@sample_account', order: 6, active: true },
    { key: '団体紹介', label: '団体紹介', category: '団体', type: '長文', options: '', format: '', required: false, defaultValue: '', example: 'サンプル団体は、宇宙に関するイベントの企画や勉強会を行う架空の学生団体です。', order: 7, active: true },
    { key: '担当者名', label: '先方の担当者名', category: '団体', type: '短文', options: '', format: '', required: false, defaultValue: '', example: '見本 花子', order: 8, active: true },
    { key: '担当者メール', label: '先方の担当者メール', category: '団体', type: '短文', options: '', format: '', required: false, defaultValue: '', example: 'contact@example.com', order: 9, active: true },
    { key: '締結日', label: '締結日', category: '案件', type: '日付', options: '', format: 'YYYY年M月D日', required: true, defaultValue: '', example: '2026-09-24', order: 10, active: true },
    { key: '公開日', label: '告知の公開日', category: '案件', type: '日付', options: '', format: 'YYYY年M月D日（曜）', required: false, defaultValue: '', example: '2026-10-01', order: 11, active: true },
    { key: '連携内容', label: '連携内容', category: '案件', type: '長文', options: '', format: '', required: true, defaultValue: '', example: 'イベントの共同開催や、SNSでの相互の情報発信を行います。', order: 12, active: true },
    { key: '連携期間', label: '連携期間（か月）', category: '案件', type: '数値', options: '', format: '', required: false, defaultValue: '12', example: '12', order: 13, active: true },
    { key: '告知URL', label: '告知ページのURL', category: '案件', type: 'URL', options: '', format: '', required: false, defaultValue: '', example: 'https://example.com/news/sample', order: 14, active: true },
    { key: '一言コメント', label: '担当者からの一言', category: '案件', type: '長文', options: '', format: '', required: false, defaultValue: '', example: '一緒に新しい挑戦ができることを楽しみにしています。', order: 15, active: true },
  ],
  settings: [
    { key: '署名', value: 'サンプル運営事務局', description: 'メール・HPニュースの末尾に入る署名' },
    { key: '運営団体名', value: 'サンプル運営フォーラム', description: '自団体の名称' },
    { key: '公式ハッシュタグ', value: '#サンプル運営 #パートナー', description: 'SNS投稿の末尾に入れるハッシュタグ' },
    { key: '問い合わせ先', value: 'info@example.com', description: '問い合わせ先のメールアドレス' },
  ],
  orgs: [
    {
      id: 'O001', logoFileId: '', active: true,
      values: {
        '団体名': 'サンプル団体', '団体区分': '学生団体', '代表者名': '見本 太郎', '団体URL': 'https://example.com',
        'Xアカウント': '@sample_account', 'Instagramアカウント': '@sample_account',
        '団体紹介': 'サンプル団体は、宇宙に関するイベントの企画や勉強会を行う架空の学生団体です。',
        '担当者名': '見本 花子', '担当者メール': 'contact@example.com',
      },
    },
    {
      id: 'O002', logoFileId: '', active: true,
      values: {
        '団体名': 'サンプル株式会社', '団体区分': '企業', '代表者名': '例示 一郎', '団体URL': 'https://example.org',
        'Xアカウント': '@sample_company', 'Instagramアカウント': '',
        '団体紹介': 'サンプル株式会社は、衛星データを使ったサービスを開発する架空の企業です。',
        '担当者名': '例示 次郎', '担当者メール': 'partner@example.org',
      },
    },
  ],
  templates: [
    { id: 'T001', name: '締結告知メール（共通）', setId: 'S001', mediaId: 'M001', rank: '共通', format: 'テキスト', fileId: '', active: true },
    { id: 'T002', name: '締結告知X（ゴールド・スレッド）', setId: 'S001', mediaId: 'M002', rank: 'ゴールド', format: 'テキスト', fileId: '', active: true },
    { id: 'T003', name: '締結告知X（共通）', setId: 'S001', mediaId: 'M002', rank: '共通', format: 'テキスト', fileId: '', active: true },
    { id: 'T004', name: '締結告知Instagram（共通）', setId: 'S001', mediaId: 'M003', rank: '共通', format: 'テキスト', fileId: '', active: true },
    { id: 'T005', name: '締結告知note（ゴールド）', setId: 'S001', mediaId: 'M004', rank: 'ゴールド', format: 'テキスト', fileId: '', active: true },
    { id: 'T006', name: '締結告知note（共通）', setId: 'S001', mediaId: 'M004', rank: '共通', format: 'テキスト', fileId: '', active: true },
    { id: 'T007', name: '締結告知HPニュース（共通）', setId: 'S001', mediaId: 'M005', rank: '共通', format: 'テキスト', fileId: '', active: true },
  ],
  templateFields: [
    { templateId: 'T001', fieldKey: '件名', content: '【パートナー締結のお知らせ】{{団体名}}様' },
    { templateId: 'T001', fieldKey: '本文', content: [
      '{{団体名}}',
      '{{担当者名}}様',
      '',
      'いつもお世話になっております。{{運営団体名}}です。',
      '',
      'このたび、{{団体名}}様とのパートナー締結が完了いたしましたので、ご連絡いたします。',
      '',
      '■ 締結日',
      '{{締結日}}',
      '',
      '■ 連携内容',
      '{{連携内容}}',
      '',
      '■ 告知の公開予定',
      '{{公開日}}より、X・Instagram・note・公式サイトにて順次告知いたします。',
      '',
      'ご不明な点がございましたら、{{問い合わせ先}} までお気軽にお問い合わせください。',
      '今後ともどうぞよろしくお願いいたします。',
      '',
      '{{署名}}',
    ].join('\n') },
    { templateId: 'T002', fieldKey: '本文', content: [
      '【パートナー締結のお知らせ】',
      '{{締結日:M/D(曜)}}、{{団体名}}（{{Xアカウント}}）とゴールドパートナー契約を締結しました🤝',
      '---',
      '{{団体名}}について',
      '{{団体紹介}}',
      '---',
      '今後の連携内容',
      '{{連携内容}}',
      '',
      '詳しくはこちら👇',
      '{{告知URL}}',
      '',
      '{{公式ハッシュタグ}}',
    ].join('\n') },
    { templateId: 'T003', fieldKey: '本文', content: [
      '【パートナー締結のお知らせ】',
      '{{団体名}}（{{Xアカウント}}）とパートナー契約を締結しました。',
      '',
      '{{連携内容}}',
      '',
      '詳しくはこちら',
      '{{告知URL}}',
      '{{公式ハッシュタグ}}',
    ].join('\n') },
    { templateId: 'T004', fieldKey: '本文', content: [
      '【パートナー締結のお知らせ】',
      '',
      '{{締結日:M月D日}}、{{団体名}}（{{Instagramアカウント}}）とパートナー契約を締結しました。',
      '',
      '{{団体紹介}}',
      '',
      '▼連携内容',
      '{{連携内容}}',
      '',
      '詳しくはプロフィールのリンクからご覧ください。',
    ].join('\n') },
    { templateId: 'T004', fieldKey: 'ハッシュタグ', content: '{{公式ハッシュタグ}} #パートナー締結 #サンプル' },
    { templateId: 'T005', fieldKey: 'タイトル', content: '{{団体名}}とゴールドパートナー契約を締結しました' },
    { templateId: 'T005', fieldKey: '本文', content: [
      'こんにちは、{{運営団体名}}です。',
      '{{締結日:YYYY年M月D日（曜）}}、{{団体名}}とゴールドパートナー契約を締結しました。',
      '',
      '## {{団体名}}について',
      '{{団体紹介}}',
      '',
      '代表：{{代表者名}}',
      'Webサイト：{{団体URL}}',
      '',
      '## 連携内容',
      '{{連携内容}}',
      '連携期間：{{連携期間}}か月',
      '',
      '## 担当者からのコメント',
      '{{一言コメント}}',
      '',
      '## お問い合わせ',
      '{{問い合わせ先}}',
    ].join('\n') },
    { templateId: 'T006', fieldKey: 'タイトル', content: '{{団体名}}とパートナー契約を締結しました' },
    { templateId: 'T006', fieldKey: '本文', content: [
      'こんにちは、{{運営団体名}}です。',
      '{{締結日}}、{{団体名}}とパートナー契約を締結しました。',
      '',
      '## {{団体名}}について',
      '{{団体紹介}}',
      '',
      '## 連携内容',
      '{{連携内容}}',
      '',
      'お問い合わせ：{{問い合わせ先}}',
    ].join('\n') },
    { templateId: 'T007', fieldKey: 'タイトル', content: '{{団体名}}とのパートナー締結のお知らせ' },
    { templateId: 'T007', fieldKey: '本文', content: [
      '{{締結日:YYYY/MM/DD}}',
      '',
      '{{運営団体名}}は、{{締結日}}に{{団体名}}とパートナー契約を締結いたしました。',
      '',
      '■ {{団体名}}について',
      '{{団体紹介}}',
      '{{団体URL}}',
      '',
      '■ 連携内容',
      '{{連携内容}}',
      '',
      '■ 本件に関するお問い合わせ',
      '{{署名}}（{{問い合わせ先}}）',
    ].join('\n') },
  ],
};
